#!/bin/bash

cp -f ~/.bashrc ~/.basrch.bkp

echo "PROMPT_COMMAND='PS1_CMD1=$(ip route get 1.1.1.1 | awk -F"src " '"'"'NR == 1{ split($2, a," ");print a[1]}'"'"')'; PS1='-[\[\e[38;5;39m\]\d\[\e[0m\] \[\e[38;5;197m\]\@\[\e[0m\]]-[\[\e[38;5;39m\]\u\[\e[38;5;229m\]@\[\e[38;5;197m\]\h\[\e[0m\]]-[\[\e[38;5;229m\]${PS1_CMD1}\[\e[0m\]]-\n-[\[\e[38;5;251m\]\w\[\e[0m\]] \$ '" >> ~/.bashrc
